test:
  api: http://wattsworth.local/api
  interfaces: http://XX.data_app.wattsworth.local

development:
  api: http://wattsworth.local/api
  interfaces: http://XX.data_app.wattsworth.local
  frontend: http://wattsworth.net
aws:
  api: https://wattsworth.net/api
  interfaces: https://XX.data_app.wattsworth.net
